<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2025-09-21">

<title>Week 04: Chapter 3.3-3.5 – Nonparamtric Methods Journal</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Nonparamtric Methods Journal</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../journal/index.html"> 
<span class="menu-text">Weeks</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../rubric.html"> 
<span class="menu-text">Rubric</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../checklist.html"> 
<span class="menu-text">Checklist</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#section" id="toc-section" class="nav-link active" data-scroll-target="#section">3.3</a></li>
  <li><a href="#method" id="toc-method" class="nav-link" data-scroll-target="#method">Method</a></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">Data</a></li>
  <li><a href="#assumptions" id="toc-assumptions" class="nav-link" data-scroll-target="#assumptions">Assumptions</a></li>
  <li><a href="#approach" id="toc-approach" class="nav-link" data-scroll-target="#approach">Approach</a></li>
  <li><a href="#completed-homework-problem" id="toc-completed-homework-problem" class="nav-link" data-scroll-target="#completed-homework-problem">Completed Homework Problem</a></li>
  <li><a href="#section-1" id="toc-section-1" class="nav-link" data-scroll-target="#section-1">3.4</a></li>
  <li><a href="#method-1" id="toc-method-1" class="nav-link" data-scroll-target="#method-1">Method</a></li>
  <li><a href="#assumptions-1" id="toc-assumptions-1" class="nav-link" data-scroll-target="#assumptions-1">Assumptions</a></li>
  <li><a href="#parametric-equivalent-or-proof-that-there-is-none" id="toc-parametric-equivalent-or-proof-that-there-is-none" class="nav-link" data-scroll-target="#parametric-equivalent-or-proof-that-there-is-none">Parametric equivalent (or proof that there is none)</a></li>
  <li><a href="#hypotheses" id="toc-hypotheses" class="nav-link" data-scroll-target="#hypotheses">Hypotheses</a></li>
  <li><a href="#rejection-region" id="toc-rejection-region" class="nav-link" data-scroll-target="#rejection-region">Rejection Region</a></li>
  <li><a href="#test-statistic-andor-p-value" id="toc-test-statistic-andor-p-value" class="nav-link" data-scroll-target="#test-statistic-andor-p-value">Test Statistic and/or p-value</a></li>
  <li><a href="#r-function" id="toc-r-function" class="nav-link" data-scroll-target="#r-function">R function</a></li>
  <li><a href="#completed-homework-problem-1" id="toc-completed-homework-problem-1" class="nav-link" data-scroll-target="#completed-homework-problem-1">Completed Homework Problem</a></li>
  <li><a href="#section-2" id="toc-section-2" class="nav-link" data-scroll-target="#section-2">3.5</a></li>
  <li><a href="#method-2" id="toc-method-2" class="nav-link" data-scroll-target="#method-2">Method</a></li>
  <li><a href="#assumptions-2" id="toc-assumptions-2" class="nav-link" data-scroll-target="#assumptions-2">Assumptions</a></li>
  <li><a href="#parametric-equivalent-or-proof-that-there-is-none-1" id="toc-parametric-equivalent-or-proof-that-there-is-none-1" class="nav-link" data-scroll-target="#parametric-equivalent-or-proof-that-there-is-none-1">Parametric equivalent (or proof that there is none)</a></li>
  <li><a href="#hypotheses-1" id="toc-hypotheses-1" class="nav-link" data-scroll-target="#hypotheses-1">Hypotheses</a></li>
  <li><a href="#rejection-region-1" id="toc-rejection-region-1" class="nav-link" data-scroll-target="#rejection-region-1">Rejection Region</a></li>
  <li><a href="#test-statistic-andor-p-value-1" id="toc-test-statistic-andor-p-value-1" class="nav-link" data-scroll-target="#test-statistic-andor-p-value-1">Test Statistic and/or p-value</a></li>
  <li><a href="#r-function-1" id="toc-r-function-1" class="nav-link" data-scroll-target="#r-function-1">R function</a></li>
  <li><a href="#completed-homework-problem-2" id="toc-completed-homework-problem-2" class="nav-link" data-scroll-target="#completed-homework-problem-2">Completed Homework Problem</a></li>
  <li><a href="#method-3" id="toc-method-3" class="nav-link" data-scroll-target="#method-3">Method</a></li>
  <li><a href="#assumptions-3" id="toc-assumptions-3" class="nav-link" data-scroll-target="#assumptions-3">Assumptions</a></li>
  <li><a href="#parametric-equivalent-or-proof-that-there-is-none-2" id="toc-parametric-equivalent-or-proof-that-there-is-none-2" class="nav-link" data-scroll-target="#parametric-equivalent-or-proof-that-there-is-none-2">Parametric equivalent (or proof that there is none)</a></li>
  <li><a href="#hypotheses-2" id="toc-hypotheses-2" class="nav-link" data-scroll-target="#hypotheses-2">Hypotheses</a></li>
  <li><a href="#rejection-region-2" id="toc-rejection-region-2" class="nav-link" data-scroll-target="#rejection-region-2">Rejection Region</a></li>
  <li><a href="#test-statistic-andor-p-value-2" id="toc-test-statistic-andor-p-value-2" class="nav-link" data-scroll-target="#test-statistic-andor-p-value-2">Test Statistic and/or p-value</a></li>
  <li><a href="#r-function-2" id="toc-r-function-2" class="nav-link" data-scroll-target="#r-function-2">R function</a></li>
  <li><a href="#completed-homework-problem-3" id="toc-completed-homework-problem-3" class="nav-link" data-scroll-target="#completed-homework-problem-3">Completed Homework Problem</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Week 04: Chapter 3.3-3.5</h1>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">2025-09-21</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="section" class="level2">
<h2 class="anchored" data-anchor-id="section">3.3</h2>
</section>
<section id="method" class="level2">
<h2 class="anchored" data-anchor-id="method">Method</h2>
<p>Tolerance limits are different from confidence intervals in that they provide an interval within which at least a proportion <span class="math inline">\(q\)</span> of the population lies, within probability <span class="math inline">\(1-\alpha\)</span> or more that the stated interval does indeed “contain” the proportion <span class="math inline">\(q\)</span> of the population.</p>
<p>With a sample size of <span class="math inline">\(n\)</span>, there is a probability that at least <span class="math inline">\(1-\alpha\)</span> that at least <span class="math inline">\(q\)</span> [or <span class="math inline">\((100)(q)%\)</span>] of the population is between <span class="math inline">\(X^{(r)}\)</span> and <span class="math inline">\(X^{(n+1-m)}\)</span> inclusive. For one-sided tolerance regions let either <span class="math inline">\(r\)</span> or <span class="math inline">\(m = 0\)</span>, where <span class="math inline">\(X^{(r)}\)</span> and <span class="math inline">\(X^{(n+1)}\)</span> are considered to be <span class="math inline">\(-\infty\)</span> and <span class="math inline">\(+\infty\)</span> respectively, and then proceed with methods.</p>
</section>
<section id="data" class="level2">
<h2 class="anchored" data-anchor-id="data">Data</h2>
<p>The data consists of a random sample <span class="math inline">\(X_1, X_2, ..., X_n\)</span> from a larger population. A confidence coefficient is chosen, <span class="math inline">\(1-\alpha\)</span> and a pair of integers <span class="math inline">\(r\)</span> and <span class="math inline">\(m\)</span> are chosen as well.</p>
<p>Important Note! We try to make the statement: “The probability is <span class="math inline">\(1-\alpha\)</span> that the random interval from <span class="math inline">\(X^{(r)}\)</span> to <span class="math inline">\(X^{(n+1-m)}\)</span> inclusive contains a proportion <span class="math inline">\(q\)</span> or more of the population.”</p>
</section>
<section id="assumptions" class="level2">
<h2 class="anchored" data-anchor-id="assumptions">Assumptions</h2>
<ol type="1">
<li>The <span class="math inline">\(X_1, X_2, ..., X_n\)</span> are a random sample.</li>
<li>The measurement scale is at least ordinal.</li>
</ol>
</section>
<section id="approach" class="level2">
<h2 class="anchored" data-anchor-id="approach">Approach</h2>
<p>Approach A (to find <span class="math inline">\(n\)</span>):</p>
<ul>
<li>Used when we want to determine the required sample size <span class="math inline">\(n\)</span> after selecting a desired population proportion <span class="math inline">\(q\)</span></li>
<li>If <span class="math inline">\(r+m = 1\)</span>, or if either <span class="math inline">\(r\)</span> or <span class="math inline">\(m = 0\)</span> as a one-sided tolerance limit, read <span class="math inline">\(n\)</span> directly from Table A5 to find the appropriate values of <span class="math inline">\(\alpha\)</span> and <span class="math inline">\(q\)</span>.</li>
<li>If <span class="math inline">\(r+m=2\)</span>, read <span class="math inline">\(n\)</span> from Table A6 for the appropriate values of <span class="math inline">\(\alpha\)</span> and <span class="math inline">\(q\)</span>.</li>
<li>If Table A5 and A6 are not appropriate, use the approximation:</li>
</ul>
<p><span class="math display">\[
n \cong \frac 14 x_{1-\alpha} \frac {1+q} {1-q} + \frac 12 (r+m-1)
\]</span> where <span class="math inline">\(x_{1-\alpha}\)</span> is the <span class="math inline">\((1-\alpha)\)</span> quantile of a chi-squared random variable with <span class="math inline">\(2(r+m)\)</span> degrees of freedom, obtained from Table A2.</p>
<p>Approach B (to find <span class="math inline">\(q\)</span>):</p>
<ul>
<li>Used when we want to determine the population proportion <span class="math inline">\(q\)</span> for a given sample size <span class="math inline">\(n\)</span></li>
<li>For a given sample size <span class="math inline">\(n\)</span> and selected values of <span class="math inline">\(\alpha\)</span>, <span class="math inline">\(r\)</span>, and <span class="math inline">\(m\)</span>, the approximate value of <span class="math inline">\(q\)</span>, the proportion of the population, is given by:</li>
</ul>
<p><span class="math display">\[
q = \frac {4n-2(r+m-1)-x_{1-\alpha}} {4n-2(r+m-1)+x_{1-\alpha}}
\]</span></p>
</section>
<section id="completed-homework-problem" class="level2">
<h2 class="anchored" data-anchor-id="completed-homework-problem">Completed Homework Problem</h2>
<ol start="7" type="1">
<li>A fitness gym has measured the percentage of fat on 86 of its members.</li>
</ol>
<ol type="a">
<li>At least what percent of its members have fat percentage between the smallest and largest of the percentages measured on the 86 members of the sample, with 95% certainty? With 90% certainty?</li>
<li>At least what percent of its members have fat percentage between <span class="math inline">\(X^{(2)}\)</span> and <span class="math inline">\(X^{(85)}\)</span> with 95% certainty? With 90% certainty?</li>
</ol>
<p>Part a:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># part (a): [X(1), X(86)]</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>p95 <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> <span class="fl">0.05</span><span class="sc">^</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">86</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>p90 <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> <span class="fl">0.10</span><span class="sc">^</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">86</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>p95</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.03423437</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>p90</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.02641899</code></pre>
</div>
</div>
<p>With 95% confidence, we can say at least 3.42% of the population lies between the smallest and largest observed fat percentages. With 90% confidence, we can say at least 2.64% of the population lies between the smallest and largest observed fat percentages.</p>
<p>Part b:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># part (b): [X(2), X(85)]</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>p95 <span class="ot">&lt;-</span> <span class="fu">qbeta</span>(<span class="fl">0.05</span>, <span class="dv">84</span>, <span class="dv">3</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>p90 <span class="ot">&lt;-</span> <span class="fu">qbeta</span>(<span class="fl">0.10</span>, <span class="dv">84</span>, <span class="dv">3</span>)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>p95</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9286002</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>p90</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9392982</code></pre>
</div>
</div>
<p>With 95% confidence, at least 92.86% of the population have fat percentage between <span class="math inline">\(X^{(2)}\)</span> and <span class="math inline">\(X^{(85)}\)</span>. With 90% confidence, at least 93.93% of the population have fat percentage between <span class="math inline">\(X^{(2)}\)</span> and <span class="math inline">\(X^{(85)}\)</span>.</p>
</section>
<section id="section-1" class="level2">
<h2 class="anchored" data-anchor-id="section-1">3.4</h2>
</section>
<section id="method-1" class="level2">
<h2 class="anchored" data-anchor-id="method-1">Method</h2>
<p>The sign test is the more simple version of the binomial test with <span class="math inline">\(p^* = 1/2 = 1 - p^*\)</span>. The sign test is useful when trying to find out whether one random variable in a pair <span class="math inline">\((X, Y)\)</span> is larger than the other random variable in the pair. The data will consist of observations on a bivariate random sample <span class="math inline">\((X_1, Y_1), (X_2, Y_2), ... , (X_n, Y_n)\)</span> where there are <span class="math inline">\(n'\)</span> pairs of observations. With each pair, a comparison is made, and the comparison is then classified as either “+” (plus, if <span class="math inline">\(X_i &lt; Y_i\)</span>) or “-” (minus, if <span class="math inline">\(X_i &gt; Y_i\)</span>) or “0” (tie, if <span class="math inline">\(X_i = Y_i\)</span>).</p>
</section>
<section id="assumptions-1" class="level2">
<h2 class="anchored" data-anchor-id="assumptions-1">Assumptions</h2>
<ol type="1">
<li>The bivariate random variables <span class="math inline">\((X_i, Y_i), i = 1, 2, ..., n'\)</span> are mutually independent.</li>
<li>The measurement scale is at least ordinal within each pair (i.e.&nbsp;each can be classified as plus, minus, or tie).</li>
<li>Pairs are internally consistent (i.e.&nbsp;if <span class="math inline">\(P(+) &gt; P(-)\)</span> for one pair, it is for all pairs).</li>
</ol>
</section>
<section id="parametric-equivalent-or-proof-that-there-is-none" class="level2">
<h2 class="anchored" data-anchor-id="parametric-equivalent-or-proof-that-there-is-none">Parametric equivalent (or proof that there is none)</h2>
<ul>
<li>The Wilcoxon signed rank test is the parametric equivalent if we assume the difference <span class="math inline">\(Y_i - X_i\)</span> are random variables with a symmetric distribution function (i.e.&nbsp;the distribution function of a random variable <span class="math inline">\(Z\)</span> is symmetric about some point <span class="math inline">\(c\)</span> if <span class="math inline">\(P(Z \leq c - x) = P(Z \geq c + x)\)</span> for all <span class="math inline">\(x\)</span>).</li>
<li>The paired <span class="math inline">\(t\)</span>-test is the parametric equivalent if the differences <span class="math inline">\(Y_i - X_i\)</span> are independent and identically distributed normal random variables.</li>
</ul>
</section>
<section id="hypotheses" class="level2">
<h2 class="anchored" data-anchor-id="hypotheses">Hypotheses</h2>
<ul>
<li><span class="math inline">\(H_0\)</span>: <span class="math inline">\(P(+) = P(-)\)</span> (two-tailed) | <span class="math inline">\(P(+) \geq P(-)\)</span> (left-tailed) | <span class="math inline">\(P(+) \leq P(-)\)</span> (right-tailed)</li>
<li><span class="math inline">\(H_A\)</span>: <span class="math inline">\(P(+) \neq P(-)\)</span> (two-tailed) | <span class="math inline">\(P(+) &lt; P(-)\)</span> (left-tailed) | <span class="math inline">\(P(+) &gt; P(-)\)</span> (right-tailed)</li>
</ul>
<p>In terms of null distribution, it could be interpreted in the following ways:</p>
<ul>
<li><p>Two-tailed:</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: <span class="math inline">\(E(X_i) = E(Y_i)\)</span> for all i (for means) | <span class="math inline">\(M\)</span> of <span class="math inline">\(X_i = M\)</span> of <span class="math inline">\(Y_i\)</span> for all i (for medians)</li>
<li><span class="math inline">\(H_A\)</span>: <span class="math inline">\(E(X_i) \neq E(Y_i)\)</span> for all i | <span class="math inline">\(M\)</span> of <span class="math inline">\(X_i \neq M\)</span> of <span class="math inline">\(Y_i\)</span> for all i</li>
</ul></li>
<li><p>Left-tailed:</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: <span class="math inline">\(E(X_i) \leq E(Y_i)\)</span> for all i (for means) | <span class="math inline">\(M\)</span> of <span class="math inline">\(X_i \leq M\)</span> of <span class="math inline">\(Y_i\)</span> for all i (for medians)</li>
<li><span class="math inline">\(H_A\)</span>: <span class="math inline">\(E(X_i) &gt; E(Y_i)\)</span> for all i | <span class="math inline">\(M\)</span> of <span class="math inline">\(X_i &gt; M\)</span> of <span class="math inline">\(Y_i\)</span> for all i</li>
</ul></li>
<li><p>Right-tailed:</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: <span class="math inline">\(E(X_i) \geq E(Y_i)\)</span> for all i (for means) | <span class="math inline">\(M\)</span> of <span class="math inline">\(X_i \geq M\)</span> of <span class="math inline">\(Y_i\)</span> for all i (for medians)</li>
<li><span class="math inline">\(H_A\)</span>: <span class="math inline">\(E(X_i) &lt; E(Y_i)\)</span> for all i | <span class="math inline">\(M\)</span> of <span class="math inline">\(X_i &lt; M\)</span> of <span class="math inline">\(Y_i\)</span> for all i</li>
</ul></li>
</ul>
</section>
<section id="rejection-region" class="level2">
<h2 class="anchored" data-anchor-id="rejection-region">Rejection Region</h2>
<p>Two-tailed:</p>
<ul>
<li>For <span class="math inline">\(n \leq 20\)</span>, use Table A3 with <span class="math inline">\(n\)</span> and <span class="math inline">\(p=1/2\)</span>; find about <span class="math inline">\(\alpha/2\)</span> and call it <span class="math inline">\(\alpha_1\)</span>. The value of <span class="math inline">\(y\)</span> corresponding to <span class="math inline">\(\alpha_1\)</span> is <span class="math inline">\(t\)</span>.</li>
<li>Reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(T \leq t\)</span> or if <span class="math inline">\(T \geq n - t\)</span> at a level of significance of <span class="math inline">\(2\alpha_1\)</span></li>
<li>For <span class="math inline">\(n &gt; 20\)</span>, use the normal approximation to get: <span class="math display">\[
t = \frac{1}{2} (n + z_{\alpha/2} \sqrt{n})
\]</span> where <span class="math inline">\(z_{\alpha/2}\)</span> is obtained from Table A1. And, if <span class="math inline">\(\alpha = 0.05\)</span> and <span class="math inline">\(z_{\alpha/2} = (-1.96)\)</span>, then: <span class="math display">\[
t = \frac{n}{2} - \sqrt{n}
\]</span></li>
</ul>
<p>Left-tailed:</p>
<ul>
<li>Note: small values of <span class="math inline">\(T\)</span> indicate that a minus is more probable than a plus (agreeing with <span class="math inline">\(H_1\)</span>)</li>
<li>For <span class="math inline">\(n \leq 20\)</span>, use Table A3 with <span class="math inline">\(n\)</span> and <span class="math inline">\(p=1/2\)</span>; find about <span class="math inline">\(\alpha\)</span> and call it <span class="math inline">\(\alpha_1\)</span>. The value of <span class="math inline">\(y\)</span> corresponding to <span class="math inline">\(\alpha_1\)</span> is <span class="math inline">\(t\)</span>.</li>
<li>For <span class="math inline">\(n &gt; 20\)</span>, <span class="math inline">\(t\)</span> is found using this approximation: <span class="math display">\[
t = \frac{1}{2} (n + z_{\alpha} \sqrt{n})
\]</span></li>
<li>Reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(T \leq t\)</span> at a significance level of <span class="math inline">\(\alpha_1\)</span> or <span class="math inline">\(\alpha\)</span>.</li>
</ul>
<p>Right-tailed:</p>
<ul>
<li>Note: big values of <span class="math inline">\(T\)</span> indicate that a plus is more probable than a minus (agreeing with <span class="math inline">\(H_1\)</span>)</li>
<li>For <span class="math inline">\(n \leq 20\)</span>, use Table A3 with <span class="math inline">\(n\)</span> and <span class="math inline">\(p=1/2\)</span>; find about <span class="math inline">\(\alpha\)</span> and call it <span class="math inline">\(\alpha_1\)</span>. The value of <span class="math inline">\(y\)</span> corresponding to <span class="math inline">\(\alpha_1\)</span> is <span class="math inline">\(t\)</span>. (same as left-tailed test)</li>
<li>For <span class="math inline">\(n &gt; 20\)</span>, <span class="math inline">\(t\)</span> is found using the same approximation as the left-tailed test.</li>
</ul>
</section>
<section id="test-statistic-andor-p-value" class="level2">
<h2 class="anchored" data-anchor-id="test-statistic-andor-p-value">Test Statistic and/or p-value</h2>
<ul>
<li>Test Statistic: <span class="math inline">\(T\)</span> is the number of “plus” pairs (i.e.&nbsp;<span class="math inline">\(T=\)</span> number of pairs <span class="math inline">\((X_i, Y_i)\)</span> where <span class="math inline">\(X_i &lt; Y_i\)</span>).</li>
<li>The null distribution of <span class="math inline">\(T\)</span> is the binomial distribution with <span class="math inline">\(p = 1/2\)</span> and <span class="math inline">\(n=\)</span> number of noted pairs (i.e.&nbsp;disregard all tied pairs <span class="math inline">\(X=Y\)</span> and let <span class="math inline">\(n=\)</span> total number of pluses and minuses). Normal approximation is used for <span class="math inline">\(n&gt;20\)</span>.</li>
<li>The p-value is obtained differently for the different forms:
<ul>
<li>Two-tailed: p-value is twice the smaller of the probabilities that <span class="math inline">\(Y \leq\)</span> or <span class="math inline">\(\geq\)</span> the observed value of <span class="math inline">\(T\)</span> (found from Table A3 for <span class="math inline">\(n \leq 20\)</span>, Table A1 if <span class="math inline">\(n &gt; 20\)</span>)</li>
<li>Left-tailed: p-value is the probability that <span class="math inline">\(Y \leq\)</span> observed value of <span class="math inline">\(T\)</span></li>
<li>Right-tailed: p-value is the probability that <span class="math inline">\(Y \geq\)</span> observed value of <span class="math inline">\(T\)</span></li>
</ul></li>
</ul>
</section>
<section id="r-function" class="level2">
<h2 class="anchored" data-anchor-id="r-function">R function</h2>
<p>R function for sign test (obtained from https://people.stat.sc.edu/hitchcock/Rexamples518section3_4.txt)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>sign.test<span class="ot">&lt;-</span><span class="cf">function</span>(<span class="at">x=</span><span class="dv">0</span>,<span class="at">y=</span><span class="cn">NULL</span>,<span class="at">alternative=</span><span class="st">"two.sided"</span>){</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  n<span class="ot">&lt;-</span><span class="fu">sum</span>((x<span class="sc">-</span>y)<span class="sc">!=</span><span class="dv">0</span>)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  T<span class="ot">&lt;-</span><span class="fu">sum</span>(x<span class="sc">&lt;</span>y)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (alternative<span class="sc">==</span><span class="st">"less"</span>) {</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>    p.value<span class="ot">&lt;-</span><span class="fu">pbinom</span>(T,n,<span class="fl">0.5</span>)}</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (alternative<span class="sc">==</span><span class="st">"greater"</span>){</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>    p.value<span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">-</span><span class="fu">pbinom</span>(T<span class="dv">-1</span>,n,<span class="fl">0.5</span>)}</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (alternative<span class="sc">==</span><span class="st">"two.sided"</span>){</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>    p.value<span class="ot">&lt;-</span><span class="dv">2</span><span class="sc">*</span><span class="fu">min</span>(<span class="dv">1</span><span class="sc">-</span><span class="fu">pbinom</span>(T<span class="dv">-1</span>,n,<span class="fl">0.5</span>),<span class="fu">pbinom</span>(T,n,<span class="fl">0.5</span>))}</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">list</span>(<span class="at">n=</span>n,<span class="at">alternative=</span>alternative,<span class="at">T=</span>T,<span class="at">p.value=</span>p.value)}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="completed-homework-problem-1" class="level2">
<h2 class="anchored" data-anchor-id="completed-homework-problem-1">Completed Homework Problem</h2>
<ol start="2" type="1">
<li>Six students went on a diet in an attempt to lose weight, with the following results: (given in code below). Is the diet an effective means of losing weight?</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co">#create a data set w/ the paired data given</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>weight_before <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">174</span>, <span class="dv">191</span>, <span class="dv">188</span>, <span class="dv">182</span>, <span class="dv">201</span>, <span class="dv">188</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>weight_after <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">165</span>, <span class="dv">186</span>, <span class="dv">183</span>, <span class="dv">178</span>, <span class="dv">203</span>, <span class="dv">181</span>)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="fu">sign.test</span>(<span class="at">x=</span>weight_before, <span class="at">y=</span>weight_after, <span class="at">alternative=</span><span class="st">"less"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$n
[1] 6

$alternative
[1] "less"

$T
[1] 1

$p.value
[1] 0.109375</code></pre>
</div>
</div>
<p><strong>Hypotheses</strong></p>
<ul>
<li><span class="math inline">\(H_0:\)</span> <span class="math inline">\(P(+) \geq P(-)\)</span>, where <span class="math inline">\(P(+) = P\)</span>(weight_before &lt; weight_after) and <span class="math inline">\(P(-) = P\)</span>(weight_before &gt; weight_after)</li>
<li><span class="math inline">\(H_1:\)</span> <span class="math inline">\(P(+) &lt; P(-)\)</span></li>
</ul>
<p><strong>Test Statistic and <em>p</em>-Value</strong></p>
<ul>
<li><span class="math inline">\(T = 1\)</span></li>
<li><span class="math inline">\(p = 0.109375\)</span></li>
</ul>
<p><strong>Rejection Region</strong></p>
<ul>
<li>Reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(p &lt; \alpha\)</span>; <span class="math inline">\(\alpha=0.05\)</span>.</li>
</ul>
<p><strong>Conclusion/Interpretation</strong></p>
<ul>
<li><p>Fail to reject <span class="math inline">\(H_0\)</span>.</p></li>
<li><p>There is not sufficient evidence to suggest that the diet is an effective means of losing weight.</p></li>
</ul>
</section>
<section id="section-2" class="level2">
<h2 class="anchored" data-anchor-id="section-2">3.5</h2>
</section>
<section id="method-2" class="level2">
<h2 class="anchored" data-anchor-id="method-2">Method</h2>
<p>The McNemar test aims to answer the question: “Can we detect a difference between the probability of (0,1) and the probability of (1,0)?” This is a different version of the sign test where the data is on a nominal measurement scale with categories “0” and “1”. The data will consist of observations on <span class="math inline">\(n'\)</span> independent bivariate random variables <span class="math inline">\((X_i, Y_i), i = 1, 2, ..., n'\)</span>.</p>
<p>The data is usually organized into a contingency table, where <span class="math inline">\(a\)</span> = the number of pairs where <span class="math inline">\(X_i = 0\)</span> and <span class="math inline">\(Y_i = 0\)</span>; <span class="math inline">\(b\)</span> = the number of pairs where <span class="math inline">\(X_i = 0\)</span> and <span class="math inline">\(Y_i = 1\)</span>; <span class="math inline">\(c\)</span> = the number of pairs where <span class="math inline">\(X_i = 1\)</span> and <span class="math inline">\(Y_i = 0\)</span>; and <span class="math inline">\(d\)</span> = the number of pairs where <span class="math inline">\(X_i = 1\)</span> and <span class="math inline">\(Y_i = 1\)</span>.</p>
</section>
<section id="assumptions-2" class="level2">
<h2 class="anchored" data-anchor-id="assumptions-2">Assumptions</h2>
<ol type="1">
<li>The pairs <span class="math inline">\((X_i, Y_i)\)</span> are mutually independent.</li>
<li>The measurement scale is nominal with two categories “0” and “1” for all <span class="math inline">\(X_i\)</span> and <span class="math inline">\(Y_i\)</span></li>
<li>The difference <span class="math inline">\(P(X_i = 0, Y_i = 1) - P(X_i = 1, Y_i = 0)\)</span> is negative/zero/positive for all <span class="math inline">\(i\)</span></li>
</ol>
</section>
<section id="parametric-equivalent-or-proof-that-there-is-none-1" class="level2">
<h2 class="anchored" data-anchor-id="parametric-equivalent-or-proof-that-there-is-none-1">Parametric equivalent (or proof that there is none)</h2>
<p>The McNemar test is equivalent to the paired sample t-tests but for dichotomous dependent variables, as opposed to for continuous dependent variables by the paired sample tests (via https://real-statistics.com/non-parametric-tests/mcnemars-test/).</p>
</section>
<section id="hypotheses-1" class="level2">
<h2 class="anchored" data-anchor-id="hypotheses-1">Hypotheses</h2>
<ul>
<li><span class="math inline">\(H_0\)</span>: <span class="math inline">\(P(X_i = 0, Y_i = 1) = P(X_i = 1, Y_i = 0)\)</span> for all <span class="math inline">\(i\)</span></li>
<li><span class="math inline">\(H_A\)</span>: <span class="math inline">\(P(X_i = 0, Y_i = 1) \neq P(X_i = 1, Y_i = 0)\)</span> for all <span class="math inline">\(i\)</span></li>
</ul>
<p>These hypotheses can also be interpreted like this, if we add <span class="math inline">\(P(X_i = 0, Y_i = 0)\)</span> to both sides:</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: <span class="math inline">\(P(X_i = 0) = P(Y_i = 0)\)</span> for all <span class="math inline">\(i\)</span> | <span class="math inline">\(P(X_i = 1) = P(Y_i = 1)\)</span> for all <span class="math inline">\(i\)</span></li>
<li><span class="math inline">\(H_A\)</span>: <span class="math inline">\(P(X_i = 0) \neq P(Y_i = 0)\)</span> for all <span class="math inline">\(i\)</span> | <span class="math inline">\(P(X_i = 1) \neq P(Y_i = 1)\)</span> for all <span class="math inline">\(i\)</span></li>
</ul>
</section>
<section id="rejection-region-1" class="level2">
<h2 class="anchored" data-anchor-id="rejection-region-1">Rejection Region</h2>
<ul>
<li>Let <span class="math inline">\(n=b+c\)</span>. If <span class="math inline">\(n \leq 20\)</span>, use Table A3. Enter table with <span class="math inline">\(p=1/2\)</span> and <span class="math inline">\(n=b+c\)</span> to find approximately <span class="math inline">\(\alpha/2\)</span> (called <span class="math inline">\(\alpha_1\)</span>). The corresponding value of <span class="math inline">\(y\)</span> is <span class="math inline">\(t\)</span>. Reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(T_2 \leq t\)</span> or if <span class="math inline">\(T_2 \geq n - t\)</span> at a significance level of <span class="math inline">\(2\alpha_1\)</span>.</li>
<li>If <span class="math inline">\(n&gt;20\)</span>, use <span class="math inline">\(T_1\)</span> and Table A2. Reject <span class="math inline">\(H_0\)</span> at a level of significance <span class="math inline">\(\alpha\)</span> if <span class="math inline">\(T_1\)</span> exceeds the <span class="math inline">\((1-\alpha)\)</span> quantile of a chi-squared random variable with 1 degree of freedom.</li>
</ul>
</section>
<section id="test-statistic-andor-p-value-1" class="level2">
<h2 class="anchored" data-anchor-id="test-statistic-andor-p-value-1">Test Statistic and/or p-value</h2>
<ul>
<li>Test Statistic:
<ul>
<li>For <span class="math inline">\(b+c &gt; 20\)</span>: <span class="math inline">\(T_1 = \frac{(b-c)^2}{b+c}\)</span></li>
<li>For <span class="math inline">\(b+c \leq 20\)</span>: <span class="math inline">\(T_2 = b\)</span></li>
</ul></li>
<li>The null distribution of <span class="math inline">\(T_1\)</span> is approximately the chi-squared distribution with 1 degree of freedom when <span class="math inline">\((b+c)\)</span> is large. The exact distribution of <span class="math inline">\(T_2\)</span> is the binomial distribution with <span class="math inline">\(p=1/2\)</span> and <span class="math inline">\(n=b+c\)</span>.</li>
<li>For <span class="math inline">\(n \leq 20\)</span>, the p-value is twice the probability of <span class="math inline">\(T_2 \leq\)</span> <span class="math inline">\(\geq\)</span> the observed value (whichever is smaller). For <span class="math inline">\(n&gt;20\)</span>, the p-value is the probability of <span class="math inline">\(T_1\)</span> exceeding the observed value (as found in Table A2 for the chi-squared distribution with 1 degree of freedom).</li>
</ul>
</section>
<section id="r-function-1" class="level2">
<h2 class="anchored" data-anchor-id="r-function-1">R function</h2>
<p>R function for McNemar test (obtained from https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/mcnemar.test)</p>
<p>mcnemar.test(x, y = NULL, correct = TRUE)</p>
<p>where x is either a two-dimensional contingency table in matrix form or a factor object, y is a factor object (it will be ignored if x is a matrix), and correct indicates whether or not to apply continuity correction when computing the test statistic.</p>
</section>
<section id="completed-homework-problem-2" class="level2">
<h2 class="anchored" data-anchor-id="completed-homework-problem-2">Completed Homework Problem</h2>
<ol type="1">
<li>One hundred thirty-five citizens were selected at random and were asked to state their opinion regarding the U.S. foreign policy. Forty-three were opposed to the U.S. foreign policy. After several weeks, during which they received an informative newsletter, they were again asked their opinion, 37 were opposed, and 30 of the 37 were persons who originally were not opposed to the U.S. foreign policy. Is the change in numbers of people opposed to the U.S. foreign policy significant?</li>
</ol>
<p>Corresponding contingency table: | Before &nbsp;After | Opposed | Not Opposed | |—————-|———|————-| | Opposed | 7 | 36 | | Not Opposed | 30 | 62 |</p>
<p>From this table, let’s make a matrix of these values to enter into the McNemar test function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>foreign_policy <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">7</span>, <span class="dv">36</span>,</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>                           <span class="dv">30</span>, <span class="dv">62</span>),</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>                         <span class="at">nrow =</span> <span class="dv">2</span>,</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>                         <span class="at">byrow =</span> <span class="cn">TRUE</span>)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a><span class="fu">mcnemar.test</span>(foreign_policy, <span class="at">correct =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    McNemar's Chi-squared test with continuity correction

data:  foreign_policy
McNemar's chi-squared = 0.37879, df = 1, p-value = 0.5383</code></pre>
</div>
</div>
<p><strong>Hypotheses</strong></p>
<ul>
<li><span class="math inline">\(H_0\)</span>: <span class="math inline">\(P(X_i = 0, Y_i = 1) = P(X_i = 1, Y_i = 0)\)</span> for all <span class="math inline">\(i\)</span></li>
<li><span class="math inline">\(H_A\)</span>: <span class="math inline">\(P(X_i = 0, Y_i = 1) \neq P(X_i = 1, Y_i = 0)\)</span> for all <span class="math inline">\(i\)</span></li>
</ul>
<p>where <span class="math inline">\(X_i\)</span> represents the before opposed for person <span class="math inline">\(i\)</span> (“1” = opposed, “0” = not opposed), and <span class="math inline">\(Y_i\)</span> represents after opposed for person <span class="math inline">\(i\)</span> (“1” = opposed, “0” = not opposed).</p>
<p><strong>Test Statistic and <em>p</em>-Value</strong></p>
<ul>
<li><span class="math inline">\(\chi^2 = 0.37879\)</span></li>
<li><span class="math inline">\(p = 0.5383\)</span></li>
</ul>
<p><strong>Rejection Region</strong></p>
<ul>
<li>Reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(p &lt; \alpha\)</span>; <span class="math inline">\(\alpha=0.05\)</span>.</li>
</ul>
<p><strong>Conclusion/Interpretation</strong></p>
<ul>
<li><p>Fail to reject <span class="math inline">\(H_0\)</span>.</p></li>
<li><p>There is not sufficient evidence to suggest that the change in numbers of people opposed to the U.S. foreign policy is significant.</p></li>
</ul>
</section>
<section id="method-3" class="level2">
<h2 class="anchored" data-anchor-id="method-3">Method</h2>
<p>The Cox and Stuart test for trend involves pairing the later numbers with the earlier numbers and performing a sign test on the pairs. A trend is present if one member of each pair has a tendency to be higher/lower than the other member. A trend is not present if the sequence of numbers actually represents observations on independent and identically distributed random variables (i.e.&nbsp;no tendency for one member to exceed the other one). It can also be used to detect any specified type of nonrandom pattern (i.e.&nbsp;sine wave, periodic pattern).</p>
<p>NOTE: A sequence of numbers is said to have a trend if the later numbers in the sequence tend to be greater than the earlier numbers (upward trend) or less than the earlier numbers (downward trend).</p>
<p>The data will consist of observations on a sequence of random variables <span class="math inline">\(X_1, X_2, ..., X_{n'}\)</span>, arranged in a particular order. Group the random variables into pairs <span class="math inline">\((X_1, X_{1+c}), (X_2, X_{2+c}), ..., (X_{n'-c}, X_{n'})\)</span>, where <span class="math inline">\(c = n'/2\)</span> if <span class="math inline">\(n'\)</span> is even, otherwise <span class="math inline">\(c=(n'+1)/2\)</span>. Replace each pair <span class="math inline">\((X_i, X_{i+c})\)</span> with a “+” if <span class="math inline">\(X_i &lt; X_{i+c}\)</span> or a “-” if <span class="math inline">\(X_i &gt; X_{i+c}\)</span>. Eliminate ties. The number of untied pairs is called <span class="math inline">\(n\)</span>.</p>
</section>
<section id="assumptions-3" class="level2">
<h2 class="anchored" data-anchor-id="assumptions-3">Assumptions</h2>
<ol type="1">
<li>The random variables <span class="math inline">\(X_1, X_2, ..., X_{n'}\)</span> are mutually independent</li>
<li>The measurement scale of the <span class="math inline">\(X_i\)</span>s is at least ordinal</li>
<li>Either the <span class="math inline">\(X_i\)</span>s are identically distributed or there is a trend; meaning that the random variables are more likely to be greater than instead of less than the earlier random variables (or vice versa).</li>
</ol>
</section>
<section id="parametric-equivalent-or-proof-that-there-is-none-2" class="level2">
<h2 class="anchored" data-anchor-id="parametric-equivalent-or-proof-that-there-is-none-2">Parametric equivalent (or proof that there is none)</h2>
<p>There is no direct parametric equivalent that I am able to find.</p>
</section>
<section id="hypotheses-2" class="level2">
<h2 class="anchored" data-anchor-id="hypotheses-2">Hypotheses</h2>
<p>The hypotheses are the same as the sign test. The null hypothesis is that no trend is present. A right-tailed test is used to detect an upward trend, and a left-tailed test is used to detect a downward trend. The two-tailed test is used if the alternative hypothesis is that any type of trend (upward or downward) exists.</p>
</section>
<section id="rejection-region-2" class="level2">
<h2 class="anchored" data-anchor-id="rejection-region-2">Rejection Region</h2>
<p>The rejection region is the same as the sign test.</p>
</section>
<section id="test-statistic-andor-p-value-2" class="level2">
<h2 class="anchored" data-anchor-id="test-statistic-andor-p-value-2">Test Statistic and/or p-value</h2>
<ul>
<li>Test Statistic: <span class="math inline">\(T\)</span> = total number of +’s</li>
<li>The null distribution of <span class="math inline">\(T\)</span> is approximately the binomial distribution with <span class="math inline">\(p=1/2\)</span> and <span class="math inline">\(n=\)</span> number of untied pairs, where <span class="math inline">\(X_i \neq X_{i+c}\)</span>.</li>
<li>The p-value is calculated exactly as in the sign test.</li>
</ul>
</section>
<section id="r-function-2" class="level2">
<h2 class="anchored" data-anchor-id="r-function-2">R function</h2>
<p>R function for Cox-Stuart test (obtained from https://www.rdocumentation.org/packages/randtests/versions/1.0.1/topics/cox.stuart.test)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="do">##load in library first</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(randtests)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>cox.stuart.test(x, alternative)</p>
<p>where x is a numeric vector containing the data, and alternative is the alternative hypothesis (“two.sided” is default, can also use “left.sided” or “right.sided”).</p>
</section>
<section id="completed-homework-problem-3" class="level2">
<h2 class="anchored" data-anchor-id="completed-homework-problem-3">Completed Homework Problem</h2>
<ol start="3" type="1">
<li>In a certain city the mortality rate per 100,000 citizens due to automobile accidents for each of the last 15 years was (see below). Is there any basis for the statement that the mortality rate is increasing?</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>mortality_rate <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">17.3</span>, <span class="fl">17.9</span>, <span class="fl">18.4</span>, <span class="fl">18.1</span>, <span class="fl">18.3</span>, <span class="fl">19.6</span>, <span class="fl">18.6</span>, <span class="fl">19.2</span>, <span class="fl">17.7</span>, <span class="fl">20.0</span>, <span class="fl">19.0</span>, <span class="fl">18.8</span>, <span class="fl">19.3</span>, <span class="fl">20.2</span>, <span class="fl">19.9</span>)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cox.stuart.test</span>(mortality_rate, <span class="st">"right.sided"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Cox Stuart test

data:  mortality_rate
statistic = 7, n = 7, p-value = 0.007812
alternative hypothesis: increasing trend</code></pre>
</div>
</div>
<p><strong>Hypotheses</strong></p>
<ul>
<li><span class="math inline">\(H_0:\)</span> no trend is present</li>
<li><span class="math inline">\(H_1:\)</span> an upward/increasing trend is present</li>
</ul>
<p><strong>Test Statistic and <em>p</em>-Value</strong></p>
<ul>
<li><span class="math inline">\(T = 7\)</span></li>
<li><span class="math inline">\(p = 0.007812\)</span></li>
</ul>
<p><strong>Rejection Region</strong></p>
<ul>
<li>Reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(p &lt; \alpha\)</span>; <span class="math inline">\(\alpha=0.05\)</span>.</li>
</ul>
<p><strong>Conclusion/Interpretation</strong></p>
<ul>
<li><p>Reject <span class="math inline">\(H_0\)</span>.</p></li>
<li><p>There is sufficient evidence to suggest that the mortality rate is increasing.</p></li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/angelinascamardo\.github\.io\/Nonparametrics\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>